/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package parfumerie.vues;

/**
 *
 * @author Angele
 */
public class pnlB extends javax.swing.JPanel {

    /**
     * Creates new form pnlB
     */
    public pnlB() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        tglToutes = new javax.swing.JToggleButton();
        tglImpaye = new javax.swing.JToggleButton();
        tglPaye = new javax.swing.JToggleButton();
        tglAnnuler = new javax.swing.JToggleButton();
        panelHeader = new javax.swing.JPanel();
        panelTitre = new javax.swing.JPanel();
        lblTitre = new javax.swing.JLabel();
        btnNouveau = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        tglToutes1 = new javax.swing.JToggleButton();
        tglImpaye1 = new javax.swing.JToggleButton();
        tglPaye1 = new javax.swing.JToggleButton();
        tglAnnuler1 = new javax.swing.JToggleButton();

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 16, 12, 1));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 8, 0));

        tglToutes.setBackground(new java.awt.Color(240, 215, 140));
        tglToutes.setFont(new java.awt.Font("Baskerville Old Face", 0, 12)); // NOI18N
        tglToutes.setText("Toutes");
        tglToutes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        tglToutes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tglToutes.setFocusPainted(false);
        tglToutes.setPreferredSize(new java.awt.Dimension(90, 24));
        jPanel2.add(tglToutes);

        tglImpaye.setBackground(new java.awt.Color(242, 242, 242));
        tglImpaye.setFont(new java.awt.Font("Baskerville Old Face", 0, 12)); // NOI18N
        tglImpaye.setText("Impayée");
        tglImpaye.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        tglImpaye.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tglImpaye.setFocusPainted(false);
        tglImpaye.setPreferredSize(new java.awt.Dimension(90, 23));
        jPanel2.add(tglImpaye);

        tglPaye.setBackground(new java.awt.Color(242, 242, 242));
        tglPaye.setFont(new java.awt.Font("Baskerville Old Face", 0, 12)); // NOI18N
        tglPaye.setText("Payée");
        tglPaye.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        tglPaye.setFocusPainted(false);
        tglPaye.setPreferredSize(new java.awt.Dimension(90, 23));
        jPanel2.add(tglPaye);

        tglAnnuler.setBackground(new java.awt.Color(242, 242, 242));
        tglAnnuler.setFont(new java.awt.Font("Baskerville Old Face", 0, 12)); // NOI18N
        tglAnnuler.setText("Annuler");
        tglAnnuler.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        tglAnnuler.setFocusPainted(false);
        tglAnnuler.setPreferredSize(new java.awt.Dimension(90, 23));
        jPanel2.add(tglAnnuler);

        panelHeader.setBackground(new java.awt.Color(240, 242, 245));
        panelHeader.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 10, 20));
        panelHeader.setName("panelheader"); // NOI18N
        panelHeader.setLayout(new java.awt.BorderLayout());

        panelTitre.setName("panelTitre"); // NOI18N
        panelTitre.setLayout(new javax.swing.BoxLayout(panelTitre, javax.swing.BoxLayout.Y_AXIS));

        lblTitre.setBackground(new java.awt.Color(255, 255, 255));
        lblTitre.setFont(new java.awt.Font("Baskerville Old Face", 1, 20)); // NOI18N
        lblTitre.setText("Facture");
        panelTitre.add(lblTitre);

        panelHeader.add(panelTitre, java.awt.BorderLayout.CENTER);

        btnNouveau.setBackground(new java.awt.Color(238, 232, 170));
        btnNouveau.setFont(new java.awt.Font("Baskerville Old Face", 0, 16)); // NOI18N
        btnNouveau.setText("+ Nouvelle Facture");
        btnNouveau.setBorderPainted(false);
        btnNouveau.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNouveau.setFocusPainted(false);
        panelHeader.add(btnNouveau, java.awt.BorderLayout.EAST);

        jPanel10.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 16, 12, 1));
        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 8, 0));

        tglToutes1.setBackground(new java.awt.Color(240, 215, 140));
        tglToutes1.setFont(new java.awt.Font("Baskerville Old Face", 0, 12)); // NOI18N
        tglToutes1.setText("Toutes");
        tglToutes1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        tglToutes1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tglToutes1.setFocusPainted(false);
        tglToutes1.setPreferredSize(new java.awt.Dimension(90, 24));
        jPanel10.add(tglToutes1);

        tglImpaye1.setBackground(new java.awt.Color(242, 242, 242));
        tglImpaye1.setFont(new java.awt.Font("Baskerville Old Face", 0, 12)); // NOI18N
        tglImpaye1.setText("Impayée");
        tglImpaye1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        tglImpaye1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tglImpaye1.setFocusPainted(false);
        tglImpaye1.setPreferredSize(new java.awt.Dimension(90, 23));
        jPanel10.add(tglImpaye1);

        tglPaye1.setBackground(new java.awt.Color(242, 242, 242));
        tglPaye1.setFont(new java.awt.Font("Baskerville Old Face", 0, 12)); // NOI18N
        tglPaye1.setText("Payée");
        tglPaye1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        tglPaye1.setFocusPainted(false);
        tglPaye1.setPreferredSize(new java.awt.Dimension(90, 23));
        jPanel10.add(tglPaye1);

        tglAnnuler1.setBackground(new java.awt.Color(242, 242, 242));
        tglAnnuler1.setFont(new java.awt.Font("Baskerville Old Face", 0, 12)); // NOI18N
        tglAnnuler1.setText("Annuler");
        tglAnnuler1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        tglAnnuler1.setFocusPainted(false);
        tglAnnuler1.setPreferredSize(new java.awt.Dimension(90, 23));
        jPanel10.add(tglAnnuler1);

        panelHeader.add(jPanel10, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(183, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(482, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNouveau;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblMarque1;
    private javax.swing.JLabel lblNom1;
    private javax.swing.JLabel lblTitre;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelTitre;
    private javax.swing.JToggleButton tglAnnuler;
    private javax.swing.JToggleButton tglAnnuler1;
    private javax.swing.JToggleButton tglImpaye;
    private javax.swing.JToggleButton tglImpaye1;
    private javax.swing.JToggleButton tglPaye;
    private javax.swing.JToggleButton tglPaye1;
    private javax.swing.JToggleButton tglToutes;
    private javax.swing.JToggleButton tglToutes1;
    private javax.swing.JTextField txtMarque1;
    private javax.swing.JTextField txtNom1;
    // End of variables declaration//GEN-END:variables
}
